import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/escorts",
          "/escorts/",
          "/masajistas",
          "/moteles",
          "/hospedaje",
          "/establecimientos",
          "/profesionales",
          "/sexshop",
          "/profesional/",
          "/foro",
          "/live",
          "/premium",
          "/services",
          "/contacto",
          "/terminos",
          "/privacidad",
        ],
        disallow: [
          "/admin",
          "/dashboard",
          "/chat",
          "/chats",
          "/wallet",
          "/videocall",
          "/cuenta",
          "/favoritos",
          "/pago",
          "/ui",
          "/login",
          "/register",
          "/forgot-password",
          "/api/",
          "/_next/",
          "/perfil/",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: [
          "/admin",
          "/dashboard",
          "/chat",
          "/wallet",
          "/videocall",
          "/cuenta",
          "/favoritos",
          "/pago",
          "/login",
          "/register",
          "/api/",
        ],
      },
    ],
    sitemap: "https://uzeed.cl/sitemap.xml",
  };
}
